import express from "express";
import allGenres from "./routes/allGenres.js";
import createGenre from "./routes/createGenre.js";
import genreByid from "./routes/genreById.js";
import editGenre from "./routes/editGenre.js";
import deleteGenre from "./routes/deleteGenre.js";
const app = express();
const preFix = "/Vidvaldi";
app.use(express.json());
app.use(preFix, allGenres);
app.use(preFix, createGenre);
app.use(preFix, genreByid);
app.use(preFix, editGenre);
app.use(preFix, deleteGenre);
app.listen(5000);
