export const Genres = [
  { id: 1, name: "Action" },
  { id: 2, name: "Adventure" },
  { id: 3, name: "Animation" },
  { id: 4, name: "Biography" },
  { id: 5, name: "Comedy" },
  { id: 6, name: "Crime" },
  { id: 7, name: "Documentary" },
  { id: 8, name: "Drama" },
  { id: 9, name: "Family" },
  { id: 10, name: "Fantasy" },
  { id: 11, name: "Film-Noir" },
  { id: 12, name: "History" },
  { id: 13, name: "Horror" },
  { id: 14, name: "Music" },
  { id: 15, name: "Musical" },
  { id: 16, name: "Mystery" },
  { id: 17, name: "Romance" },
  { id: 18, name: "Sci-Fi" },
  { id: 19, name: "Sport" },
  { id: 20, name: "Thriller" },
  { id: 21, name: "War" },
  { id: 22, name: "Western" },
  { id: 23, name: "Superhero" },
  { id: 24, name: "Disaster" },
  { id: 25, name: "Psychological" },
  { id: 26, name: "Political" },
  { id: 27, name: "Epic" },
  { id: 28, name: "Experimental" },
  { id: 29, name: "Short" },
  { id: 30, name: "Animation-Adult" },
  { id: 31, name: "Children" },
  { id: 32, name: "Zombie" },
  { id: 33, name: "Vampire" },
  { id: 34, name: "Slasher" },
  { id: 35, name: "Martial Arts" },
  { id: 36, name: "Space Opera" },
  { id: 37, name: "Cyberpunk" },
  { id: 38, name: "Steampunk" },
  { id: 40, name: "Mockumentary" },
];
